server:
  port: 7777

spring:
  application:
    name: jmall-admin
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            ### nacos连接地址
            server-addr: localhost:8848
            ## nacos连接的分组
            group-id: SENTINAL_GROUP
            ###路由存储规则
            rule-type: flow
            ### 读取配置文件的 data-id
            data-id: jmall-admin-sentinal
            ###  读取培训文件类型为json
            data-type: json
micro:
  swagger:
    enabled: true
    title: jmall商城管理后台
    description: 管理后台接口文档
    version: 1.0
    base-package: top.janker.jmall.admin.controller

